---
- name: Playbook to prepare VM for openshift installer
  hosts: aap-controller
  gather_facts: false
  tasks:
    - name: Get absolute path to this Git repository # noqa: command-instead-of-module
      ansible.builtin.command: git rev-parse --show-toplevel
      delegate_to: localhost
      become: false
      run_once: true
      register: repository_path
      changed_when: false
      check_mode: false
      failed_when: repository_path.rc != 0

    - name: Copy kubeconfig to the project directory
      ansible.builtin.fetch:
        src: '/home/{{ ansible_user }}/openshift-multicluster/installer/cluster-config/auth/{{ item }}'
        dest: '{{ repository_path.stdout }}/{{ item }}'
        flat: true
      loop:
        - kubeconfig
        - kubeadmin-password
