---
- name: Playbook to setup Ansible Automation Platform
  hosts: aap-controller
  gather_facts: false
  become: true
  roles:
    - infra.aap_utilities.aap_backup
  vars:
    aap_setup_prep_setup_dir: /var/tmp/ansible-automation-platform-setup-bundle-2.4-3-x86_64/
    aap_backup_dest: /aap_backups/
  tasks:
    - name: Use a single pattern that contains a comma formatted as a list
      ansible.builtin.find:
        paths: '{{ aap_backup_dest }}'
        pattern:
          - '*backup*'
      register: find_file_result

    - name: Upload backup
      become: true
      amazon.aws.s3_object:
        access_key: '{{ minio_access_key }}'
        secret_key: '{{ minio_secret_key }}'
        endpoint_url: '{{ minio_url }}'
        bucket: aap-bundle-backups
        encrypt: false
        mode: put
        object: '{{ find_file_result.files[0].path.split("/") | last }}'
        src: '{{ find_file_result.files[0].path }}'

    - name: Cleanup backup tar
      ansible.builtin.file:
        path: '{{ find_file_result.files[0].path }}'
        state: absent
