---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  environment:
    CONTROLLER_HOST: '{{ controller_hostname }}'
    CONTROLLER_USERNAME: '{{ controller_username }}'
    CONTROLLER_PASSWORD: '{{ controller_password }}'
    CONTROLLER_VERIFY_SSL: 'false'
  vars_files:
    - ../../vars/aap-inventory.yaml
  tasks:
    - name: Create an inventory
      awx.awx.inventory:
        name: '{{ awx_inventory_name }}'
        organization: Default

    - name: Machine Credentials
      awx.awx.credential:
        name: Host Credentials
        credential_type: Machine
        organization: Default
        inputs:
          username: '{{ host_user }}'
          password: '{{ host_password }}'
          ssh_key_data: "{{ lookup('file', '/Users/vikaspogu/.ssh/id_rsa') }}"

    - name: Quay Credentials
      awx.awx.credential:
        name: Quay Credentials
        credential_type: Container Registry
        organization: Default
        inputs:
          host: quay.io
          username: '{{ quay_username }}'
          password: '{{ quay_password }}'

    - name: Ansible Vault Credentials
      awx.awx.credential:
        name: Vault Credentials
        credential_type: Vault
        organization: Default
        inputs:
          vault_password: '{{ vault_password }}'

    - name: Add EE to the controller instance
      awx.awx.execution_environment:
        name: 'Custom EE'
        image: quay.io/rhn_gps_vpogu/custom-aap24-ee-rhel8@sha256:f621dfc4ebaf5539e58f5718677d784a366e191eb06021d1f69fd8c01f175fc0
        credential: 'Quay Credentials'

    - name: '{{ awx_project_name }}'
      awx.awx.project:
        name: '{{ awx_project_name }}'
        organization: Default
        state: present
        scm_update_on_launch: true
        scm_delete_on_update: true
        scm_type: git
        default_environment: 'Custom EE'
        scm_url: https://github.com/Vikaspogu/homelab-playbooks.git

    - name: Add inventory source to inventory
      awx.awx.inventory_source:
        name: 'scm-inventory'
        description: Source for inventory
        inventory: '{{ awx_inventory_name }}'
        overwrite: true
        update_on_launch: true
        organization: Default
        source: 'scm'
        source_project: '{{ awx_project_name }}'
        source_path: 'inventory/hosts.yaml'

    - name: Create a Job Template with survey
      ansible.builtin.import_tasks: job_templates/job-template-survey.yaml
      register: job_templates_survery
      until: 'job_templates_survery is not failed'
      retries: 10
      delay: 10

    - name: Create a Job Template with no survey
      ansible.builtin.import_tasks: job_templates/job-template-no-survey.yaml
      register: job_templates
      until: 'job_templates is not failed'
      retries: 10
      delay: 10

    - name: Create 3 node ACM cluster workflow
      ansible.builtin.import_tasks: workflow_templates/acm-cluster.yaml
      register: acm_cluster_workflow
      until: 'acm_cluster_workflow is not failed'
      retries: 10
      delay: 10

    - name: Create SNO cluster workflow
      ansible.builtin.import_tasks: workflow_templates/sno-cluster.yaml
      register: sno_cluster_workflow
      until: 'sno_cluster_workflow is not failed'
      retries: 10
      delay: 10

    - name: Create destroy cluster workflow
      ansible.builtin.import_tasks: workflow_templates/destroy-cluster.yaml
      register: destroy_cluster_workflow
      until: 'destroy_cluster_workflow is not failed'
      retries: 10
      delay: 10
