---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars_files:
    - ../../vars/aap-inventory.yaml
  tasks:
    - name: Create an inventory
      awx.awx.inventory:
        name: '{{ awx_inventory_name }}'
        organization: Default
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false

    - name: Add hosts to inventory
      awx.awx.host:
        name: '{{  item }}'
        inventory: '{{ awx_inventory_name }}'
        state: present
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
      loop:
        - proxmox
        - aap-controller

    - name: Machine Credentials
      awx.awx.credential:
        name: Host Credentials
        credential_type: Machine
        organization: Default
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
        inputs:
          username: '{{ host_user }}'
          password: '{{ host_password }}'

    - name: Quay Credentials
      awx.awx.credential:
        name: Quay Credentials
        credential_type: Container Registry
        organization: Default
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
        inputs:
          host: quay.io
          username: '{{ quay_username }}'
          password: '{{ quay_password }}'

    - name: Ansible Vault Credentials
      awx.awx.credential:
        name: Vault Credentials
        credential_type: Vault
        organization: Default
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
        inputs:
          vault_password: '{{ vault_password }}'

    - name: Add EE to the controller instance
      awx.awx.execution_environment:
        name: 'Custom EE'
        image: quay.io/rhn_gps_vpogu/custom-aap24-ee-rhel8@sha256:f621dfc4ebaf5539e58f5718677d784a366e191eb06021d1f69fd8c01f175fc0
        credential: 'Quay Credentials'
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false

    - name: '{{ awx_project_name }}'
      awx.awx.project:
        name: '{{ awx_project_name }}'
        organization: Default
        state: present
        scm_update_on_launch: true
        scm_delete_on_update: true
        scm_type: git
        default_environment: 'Custom EE'
        scm_url: https://github.com/Vikaspogu/homelab-playbooks.git
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false

    - name: Create a Job Template with Survery
      awx.awx.job_template:
        name: '{{ item.name }}'
        organization: Default
        state: present
        inventory: '{{ awx_inventory_name }}'
        become_enabled: true
        playbook: '{{ item.file }}'
        project: '{{ awx_project_name }}'
        execution_environment: 'Custom EE'
        credentials:
          - 'Host Credentials'
          - 'Vault Credentials'
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
        survey_enabled: '{{ item.enable_survery }}'
        survey_spec: "{{ lookup('file', '{{item.survey_file}}') }}"
      loop:
        - {
            name: 'Proxmox - Create VM',
            file: playbooks/proxmox/create-vm.yaml,
            enable_survery: true,
            survey_file: 'surveys/create-vm.json',
          }
        - {
            name: 'Proxmox - Attach additional disk to VM',
            file: playbooks/proxmox/attach-additional-disk.yaml,
            enable_survery: true,
            survey_file: 'surveys/attach-additional-disk.json',
          }
        - {
            name: 'Proxmox - Delete VM',
            file: playbooks/proxmox/delete-vm.yaml,
            enable_survery: true,
            survey_file: 'surveys/delete-vm.json',
          }
        - {
            name: 'Proxmox - Mount ISO',
            file: playbooks/proxmox/mount-iso.yaml,
            enable_survery: true,
            survey_file: 'surveys/mount-iso.json',
          }
        - {
            name: 'Proxmox - Start VM',
            file: playbooks/proxmox/start-vm.yaml,
            enable_survery: true,
            survey_file: 'surveys/start-vm.json',
          }
        - {
            name: 'Proxmox - Upload ISO from URL',
            file: playbooks/proxmox/upload-iso.yaml,
            enable_survery: true,
            survey_file: 'surveys/upload-iso.json',
          }
        - {
            name: 'OpenShift - Prepare ACM Cluster ISO',
            file: playbooks/openshift/prepare-acm-iso.yaml,
            enable_survery: true,
            survey_file: '../openshift/surveys/prepare-acm-iso.json',
          }

    - name: Create a Job Template
      awx.awx.job_template:
        name: Proxmox - {{ item.name }}
        organization: Default
        state: present
        inventory: '{{ awx_inventory_name }}'
        become_enabled: true
        playbook: '{{ item.file }}'
        project: '{{ awx_project_name }}'
        execution_environment: 'Custom EE'
        credentials:
          - 'Host Credentials'
          - 'Vault Credentials'
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
      loop:
        - {
            name: 'OpenShift - Prepare SNO Cluster ISO',
            file: playbooks/openshift/prepare-sno-iso.yaml,
          }

    - name: Create a Workflow Template
      awx.awx.workflow_job_template:
        name: 'OpenShift - Create 3 Node ACM Cluster'
        inventory: '{{ awx_inventory_name }}'
        controller_host: '{{ controller_hostname }}'
        controller_username: '{{ controller_username }}'
        controller_password: '{{ controller_password }}'
        validate_certs: false
        workflow_nodes:
          - identifier: Prepare ISO
            unified_job_template:
              organization:
                name: Default
              name: 'OpenShift - Prepare ACM Cluster ISO'
              type: job_template
            related:
              success_nodes:
                - identifier: 'Create VM openshift-0'
                - identifier: 'Create VM openshift-1'
                - identifier: 'Create VM openshift-2'
          - identifier: Create VM openshift-0
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Create VM'
              type: job_template
            extra_data:
              vm_name: openshift-0
              cores: '12'
              memory: '51234'
              disk_size: '200'
              mac_address: '52:50:56:11:22:11'
            related:
              success_nodes:
                - identifier: 'Mount ISO openshift-0'
          - identifier: Create VM openshift-1
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Create VM'
              type: job_template
            extra_data:
              vm_name: openshift-1
              cores: '12'
              memory: '51234'
              disk_size: '200'
              mac_address: '52:50:56:11:22:22'
            related:
              success_nodes:
                - identifier: 'Mount ISO openshift-1'
          - identifier: Create VM openshift-2
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Create VM'
              type: job_template
            extra_data:
              vm_name: openshift-2
              cores: '12'
              memory: '51234'
              disk_size: '200'
              mac_address: '52:50:56:11:22:33'
            related:
              success_nodes:
                - identifier: 'Mount ISO openshift-2'
          - identifier: Mount ISO openshift-0
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Mount ISO'
              type: job_template
            extra_data:
              vm_name: openshift-0
            related:
              success_nodes:
                - identifier: 'Start VM openshift-0'
          - identifier: Mount ISO openshift-1
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Mount ISO'
              type: job_template
            extra_data:
              vm_name: openshift-1
            related:
              success_nodes:
                - identifier: 'Additional disk openshift-1'
          - identifier: Additional disk openshift-1
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Proxmox - Attach additional disk to VM'
              type: job_template
            extra_data:
              vm_name: openshift-1
            related:
              success_nodes:
                - identifier: 'Start VM openshift-1'
          - identifier: Mount ISO openshift-2
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Mount ISO'
              type: job_template
            extra_data:
              vm_name: openshift-2
            related:
              success_nodes:
                - identifier: 'Start VM openshift-2'
          - identifier: Start VM openshift-0
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Start VM'
              type: job_template
            extra_data:
              vm_name: openshift-0
            related:
              success_nodes: []
          - identifier: Start VM openshift-1
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Start VM'
              type: job_template
            extra_data:
              vm_name: openshift-1
            related:
              success_nodes: []
          - identifier: Start VM openshift-2
            unified_job_template:
              organization:
                name: Default
              name: 'Proxmox - Start VM'
              type: job_template
            extra_data:
              vm_name: openshift-2
            related:
              success_nodes: []
