---
- name: Create RHEL VM template
  ansible.builtin.import_playbook: '../proxmox/create-vm-template.yaml'
  vars:
    id: 9001
    vm_name: rhel-9.3-cloudinit-template

- name: Import CloudInit VM
  ansible.builtin.import_playbook: '../proxmox/create-cloudinit-vm.yaml'
  vars:
    vm_name: aap-controller
    template_name: rhel-9.3-cloudinit-template
    mac_address: bc:24:11:a0:6e:7a
    cores: 8
    memory: 20480
    disk_size: 212G

- name: Start AAP VM
  ansible.builtin.import_playbook: '../proxmox/start-vm.yaml'
  vars:
    vm_name: aap-controller

- name: Playbook to Create VM template
  hosts: aap-controller
  gather_facts: false
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 600

- name: Download and install AAP on the controller
  hosts: aap-controller
  gather_facts: false
  become: false
  tags: aap_installation
  roles:
    - infra.aap_utilities.aap_setup_download
    - infra.aap_utilities.aap_setup_prepare
    - infra.aap_utilities.aap_setup_install
  vars_files:
    - ../../vars/aap-inventory.vault.yaml
  pre_tasks:
    - name: Install required packages
      become: true
      ansible.builtin.dnf:
        name:
          - glibc-langpack-en
          - ansible-core
          - git
          - wget
          - unzip
          - tar
          - rsync
          - python3
          - python3-pip

    - name: Install boto and botocore python package
      become: true
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
