---
- name: Playbook to prepare VM for openshift installer
  hosts: aap-controller
  gather_facts: false
  tasks:
    - name: Download installer clients
      become: true
      ansible.builtin.unarchive:
        src: '{{ item }}'
        dest: /usr/local/bin
        remote_src: true
        mode: '0755'
      loop:
        - https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/latest/openshift-install-linux-amd64.tar.gz
        - https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/latest/openshift-client-linux.tar.gz

    - name: Install Packages
      become: true
      ansible.builtin.dnf:
        name:
          - nmstate

    - name: Clone git repo
      ansible.builtin.git:
        repo: https://github.com/Vikaspogu/openshift-multicluster.git
        dest: /home/{{ ansible_user }}/openshift-multicluster
        clone: true
        update: true

    - name: Copy installer files
      ansible.posix.synchronize:
        src: /home/{{ ansible_user }}/openshift-multicluster/installer/cluster-config
        dest: /home/{{ ansible_user }}/openshift-multicluster/installer/pxm-acm
        mode: push

    - name: Add pull secret
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/openshift-multicluster/installer/pxm-acm/install-config.yaml
        state: present
        regexp: 'pullSecret'
        line: 'pullSecret={{ redhat_pull_secret }}'

    - name: Run the agent create
      ansible.builtin.command:
        cmd: openshift-install agent create image --dir installer/pxm-acm
        chdir: /home/{{ ansible_user }}/openshift-multicluster

    # - name: Copy agent ISO
    #   ansible.posix.synchronize:
    #     src: /home/{{ ansible_user }}/openshift-multicluster/installer/pxm-acm/agent.x86_64.iso
    #     dest: /var/lib/vz/template/iso
    #   delegate_to: proxmox
