---
- name: Create ACM cluster Workflow Template
  awx.awx.workflow_job_template:
    name: 'OpenShift - Create 3 Node ACM Cluster'
    inventory: '{{ awx_inventory_name }}'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    workflow_nodes:
      - identifier: Prepare ISO
        unified_job_template:
          organization:
            name: Default
          name: 'OpenShift - Prepare ACM Cluster ISO'
          type: job_template
        extra_data:
          redhat_pull_secret: '{{ redhat_pull_secret | string }}'
        related:
          success_nodes:
            - identifier: 'Create VM openshift-0'
            - identifier: 'Create VM openshift-1'
            - identifier: 'Create VM openshift-2'
      - identifier: Create VM openshift-0
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: openshift-0
          cores: '12'
          memory: '51234'
          disk_size: '200'
          mac_address: '52:50:56:11:22:11'
        related:
          success_nodes:
            - identifier: 'Mount ISO openshift-0'
      - identifier: Create VM openshift-1
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: openshift-1
          cores: '12'
          memory: '51234'
          disk_size: '200'
          mac_address: '52:50:56:11:22:22'
        related:
          success_nodes:
            - identifier: 'Mount ISO openshift-1'
      - identifier: Create VM openshift-2
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: openshift-2
          cores: '12'
          memory: '51234'
          disk_size: '200'
          mac_address: '52:50:56:11:22:33'
        related:
          success_nodes:
            - identifier: 'Mount ISO openshift-2'
      - identifier: Mount ISO openshift-0
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: openshift-0
        related:
          success_nodes:
            - identifier: 'Start VM openshift-0'
      - identifier: Mount ISO openshift-1
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: openshift-1
        related:
          success_nodes:
            - identifier: 'Additional disk openshift-1'
      - identifier: Additional disk openshift-1
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Attach additional disk to VM'
          type: job_template
        extra_data:
          vm_name: openshift-1
        related:
          success_nodes:
            - identifier: 'Start VM openshift-1'
      - identifier: Mount ISO openshift-2
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: openshift-2
        related:
          success_nodes:
            - identifier: 'Start VM openshift-2'
      - identifier: Start VM openshift-0
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: openshift-0
        related:
          success_nodes: []
      - identifier: Start VM openshift-1
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: openshift-1
        related:
          success_nodes: []
      - identifier: Start VM openshift-2
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: openshift-2
        related:
          success_nodes: []
