---
- name: Create ACM cluster Workflow Template
  awx.awx.workflow_job_template:
    name: 'OpenShift - Create 3 Node ACM Cluster'
    inventory: '{{ awx_inventory_name }}'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    workflow_nodes:
      - identifier: Prepare ISO
        unified_job_template:
          organization:
            name: Default
          name: 'OpenShift - Prepare ACM Cluster ISO'
          type: job_template
        extra_data:
          redhat_pull_secret: '{{ redhat_pull_secret | string }}'
        related:
          success_nodes:
            - identifier: 'Create VM One'
            - identifier: 'Create VM Two'
            - identifier: 'Create VM Three'
      - identifier: Create VM One
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-0
          cores: '15'
          memory: '69632'
          disk_size: '200'
          mac_address: '52:50:56:11:22:11'
        related:
          success_nodes:
            - identifier: 'Mount ISO One'
      - identifier: Create VM Two
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-1
          cores: '15'
          memory: '69632'
          disk_size: '200'
          mac_address: '52:50:56:11:22:22'
        related:
          success_nodes:
            - identifier: 'Mount ISO Two'
      - identifier: Create VM Three
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-2
          cores: '15'
          memory: '69632'
          disk_size: '200'
          mac_address: '52:50:56:11:22:33'
        related:
          success_nodes:
            - identifier: 'Mount ISO Three'
      - identifier: Mount ISO One
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: ocp-acm-0
        related:
          success_nodes:
            - identifier: 'Start VM One'
      - identifier: Mount ISO Two
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: ocp-acm-1
        related:
          success_nodes:
            - identifier: 'Additional disk Two'
      - identifier: Additional disk Two
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Attach additional disk to VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-1
        related:
          success_nodes:
            - identifier: 'Start VM Two'
      - identifier: Mount ISO Three
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: ocp-acm-2
        related:
          success_nodes:
            - identifier: 'Start VM Three'
      - identifier: Start VM One
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-0
        related:
          success_nodes: []
      - identifier: Start VM Two
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-1
        related:
          success_nodes: []
      - identifier: Start VM Three
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: ocp-acm-2
        related:
          success_nodes: []
