---
- name: Delete destroy cluster Workflow Template
  awx.awx.workflow_job_template:
    name: 'OpenShift - Destroy Cluster'
    inventory: '{{ awx_inventory_name }}'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    workflow_nodes:
      - identifier: Delete VM openshift-0
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Delete VM'
          type: job_template
        extra_data:
          vm_name: openshift-0
      - identifier: Delete VM openshift-1
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Delete VM'
          type: job_template
        extra_data:
          vm_name: openshift-1
      - identifier: Delete VM openshift-2
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Delete VM'
          type: job_template
        extra_data:
          vm_name: openshift-2
