---
- name: Create Dev2 SNO cluster Workflow Template
  awx.awx.workflow_job_template:
    name: 'OpenShift - Create Dev1 SNO Cluster'
    inventory: '{{ awx_inventory_name }}'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    workflow_nodes:
      - identifier: Prepare SNO ISO
        unified_job_template:
          organization:
            name: Default
          name: 'OpenShift - Prepare SNO Cluster ISO'
          type: job_template
        related:
          success_nodes:
            - identifier: 'Create VM dev2-sno'
      - identifier: Create VM dev2-sno
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: dev2-sno
          cores: '12'
          memory: '51234'
          disk_size: '200'
          mac_address: '52:50:56:11:22:44'
        related:
          success_nodes:
            - identifier: 'Mount ISO dev2-sno'
      - identifier: Mount ISO dev2-sno
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: dev2-sno
          iso_name: sno.iso
        related:
          success_nodes:
            - identifier: 'Start VM dev2-sno'
      - identifier: Start VM dev2-sno
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Start VM'
          type: job_template
        extra_data:
          vm_name: dev2-sno
        related:
          success_nodes: []
