---
- name: Create OpenShift cluster Workflow Template
  awx.awx.workflow_job_template:
    name: 'OpenShift - Create 5 Node Cluster'
    inventory: '{{ awx_inventory_name }}'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    workflow_nodes:
      - identifier: Prepare ISO
        unified_job_template:
          organization:
            name: Default
          name: 'OpenShift - Prepare ACM Cluster ISO'
          type: job_template
        extra_data:
          redhat_pull_secret: '{{ redhat_pull_secret | string }}'
        related:
          success_nodes:
            - identifier: 'Create Master-0 VM'
            - identifier: 'Create Master-1 VM'
            - identifier: 'Create Master-2 VM'
            - identifier: 'Create Worker-0 VM'
            - identifier: 'Create Worker-1 VM'
      - identifier: Create Master-0 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: master-0
          cores: '13'
          memory: '57344'
          disk_size: '200'
          mac_address: '52:50:56:11:22:11'
          storage_type: lvm-nvme
          proxmox_node: proxmox
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes:
            - identifier: 'Mount ISO on Master-0 VM'
      - identifier: Create Master-1 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: master-1
          cores: '13'
          memory: '57344'
          disk_size: '200'
          mac_address: '52:50:56:11:22:22'
          storage_type: lvm-nvme
          proxmox_node: proxmox
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes:
            - identifier: 'Mount ISO on Master-1 VM'
      - identifier: Create Master-2 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: master-2
          cores: '13'
          memory: '57344'
          disk_size: '200'
          mac_address: '52:50:56:11:22:33'
          storage_type: lvm-nvme
          proxmox_node: proxmox
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes:
            - identifier: 'Mount ISO on Master-2 VM'
      - identifier: Create Worker-0 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: worker-0
          cores: '8'
          memory: '30720'
          disk_size: '200'
          mac_address: '52:50:56:11:22:44'
          storage_type: lvm-nvme
          proxmox_node: proxmox
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes:
            - identifier: 'Mount ISO on Worker-0 VM'
      - identifier: Create Worker-1 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Create VM'
          type: job_template
        extra_data:
          vm_name: worker-1
          cores: '8'
          memory: '30720'
          disk_size: '200'
          mac_address: '52:50:56:11:22:55'
          storage_type: lvm-nvme
          proxmox_node: proxmox
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes:
            - identifier: 'Mount ISO on Worker-1 VM'
      - identifier: Mount ISO on Master-0 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: master-0
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes: []
      - identifier: Mount ISO on Master-1 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: master-1
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes:
            - identifier: 'Additional disk on Master-1 VM'
      - identifier: Additional disk on Master-1 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Attach additional disk to VM'
          type: job_template
        extra_data:
          vm_name: master-1
          storage_type: lvm-nvme
          proxmox_node_ip: '10.30.30.40'
          disk_size: '500'
        related:
          success_nodes: []
      - identifier: Mount ISO on Master-2 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: master-2
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes: []
      - identifier: Mount ISO on Worker-0 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: worker-0
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes: []
      - identifier: Mount ISO on Worker-1 VM
        unified_job_template:
          organization:
            name: Default
          name: 'Proxmox - Mount ISO'
          type: job_template
        extra_data:
          vm_name: worker-1
          proxmox_node_ip: '10.30.30.40'
        related:
          success_nodes: []
