---
- name: Playbook to create a VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vars/proxmox.yaml
  tasks:
    - name: Create a VM
      community.general.proxmox_kvm:
        node: pve
        api_user: '{{ datacenter.username }}@pve'
        api_password: '{{ datacenter.password }}'
        api_host: '{{ datacenter.ip }}'
        name: '{{ vm_name }}'
        cpu: '{{ cpu_type }}'
        cores: '{{ cores }}'
        memory: '{{ memory }}'
        scsihw: "virtio-scsi-single"
        scsi:
          scsi0: '{{ storage_type }}:{{ disk_size }},iothread=1,format=raw'
        sshkeys: '{{ ssh_keys }}'
        net:
          net0: 'virtio={{ mac_address }},bridge=vmbr0,firewall=1'
