---
- name: Playbook to Create VM template
  hosts: proxmox
  gather_facts: false
  vars_files:
    - ../../vars/proxmox.yaml
  tasks:
    - name: Create cloud-init folder
      ansible.builtin.file:
        path: /var/lib/vz/snippets/
        state: directory
        mode: '0755'

    - name: Copy cloud-init file to proxmox
      ansible.builtin.template:
        src: ../../templates/{{ name }}.yaml.j2
        dest: /var/lib/vz/snippets/{{ name }}.yaml
        force: true
        mode: 'u=rw,g=r,o=r'

    - name: Retrieve information about specific VM by ID
      community.general.proxmox_vm_info:
        api_user: '{{ datacenter.username }}@pve'
        api_password: '{{ datacenter.password }}'
        api_host: '{{ datacenter.ip }}'
        node: pve
        vmid: '{{ id }}'
      register: vm_info
      delegate_to: localhost

    - name: Execute when template doesn't exist
      when: vm_info.proxmox_vms | length == 0
      block:
        - name: Download cloud image
          ansible.builtin.get_url:
            url: '{{ image_url }}'
            dest: '{{ image_path }}'
            mode: 0700

        - name: Create a VM to use as a template
          ansible.builtin.command: 'qm create {{ id }} --name {{ name }} --memory 4096 --cores 2 --net0 virtio,bridge=vmbr0 --cpu cputype=max'

        - name: Import disk image
          ansible.builtin.command: 'qm importdisk {{ id }} {{ image_path }} lvm-nvme'

        - name: Configure VM to use imported image
          ansible.builtin.command: 'qm set {{ id }} --scsihw virtio-scsi-pci --scsi0 lvm-nvme:vm-{{ id }}-disk-0'

        - name: Add cloud-init image as CDROM
          ansible.builtin.command: 'qm set {{ id }} --ide2 lvm-nvme:cloudinit'

        - name: Configure boot from the image
          ansible.builtin.command: 'qm set {{ id }} --boot c --bootdisk scsi0'

        - name: Attach serial console
          ansible.builtin.command: 'qm set {{ id }} --serial0 socket --vga serial0'

        - name: Enable agent
          ansible.builtin.command: 'qm set {{ id }} --agent enabled=1'

        - name: Set boot to start
          ansible.builtin.command: qm set {{ id }} --onboot 1

        - name: Create template
          ansible.builtin.command: 'qm template {{ id }}'
