---
- name: Playbook to start a VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vars/proxmox.yaml
  tasks:
    - name: Start a VM
      community.general.proxmox_kvm:
        node: '{{ datacenter.node }}'
        api_user: '{{ datacenter.username }}@pve'
        api_password: '{{ datacenter.password }}'
        api_host: '{{ datacenter.ip }}'
        name: '{{ vm_name }}'
        state: started
