---
- name: Playbook to Download and Upload ISO
  hosts: proxmox
  gather_facts: false
  vars_files:
    - ../../vars/proxmox.yaml
  tasks:
    - name: Download ISO from URL as a variable and upload to proxmox as ISO
      ansible.builtin.get_url:
        url: '{{ iso_url }}'
        dest: /var/lib/vz/template/iso
        mode: '0544'
