---
- name: Proxmox Create VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/proxmox.yml
  tasks:
    - name: Create proxmox k8s-7-proxmox-node  VM
      block:
        - name: Create new VM with minimal options and given vmid
          community.general.proxmox:
            api_user: root@pam
            api_password: '{{ password }}'
            api_host: "{{ proxmox }}"
            hostname: test
            ostemplate: "none"
            node: pve
            netif: '{"net0":"virtio=9a:f3:33:5a:2d:68,bridge=vmbr0"}'