---
- name: Proxmox Create VMs
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/proxmox.yml
  tasks:
    - name: Create Proxmox  VMs
      block:
        - name: Create new VM with minimal options and given vmid
          community.general.proxmox_kvm:
            api_user: '{{ username }}@pve'
            api_password: '{{ password }}'
            api_host: "{{ proxmox }}"
            name: "{{ item.name }}"
            node: "{{ node }}"
            net:
              net0: 'virtio={{ item.macadd }},bridge=vmbr0'
            cores: "{{ item.cores }}"
            memory: "{{ item.memory }}"
            sshkeys: "{{ sshKeys }}"
            autostart: "{{ item.autostart }}"
            scsi:
              scsi0: "{{ item.storage }}:{{ item.diskSize }}"
          loop: "{{ vms }}"
