---
- name: Proxmox VMs
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/proxmox.yml
  tasks:
    - name: Proxmox  VMs
      block:
        - name: Create/Destory OpenShift VMs
          community.general.proxmox_kvm:
            state: "{{ state }}"
            api_user: '{{ username }}@pve'
            api_password: '{{ password }}'
            api_host: "{{ proxmox }}"
            name: "{{ item.name }}"
            node: "{{ node }}"
            net:
              net0: 'virtio={{ item.macadd }},bridge=vmbr0'
            cores: "{{ item.cores }}"
            memory: "{{ item.memory }}"
            sshkeys: "{{ sshKeys }}"
            autostart: "{{ item.autostart }}"
            ide:
              ide0: "local:iso/agent.x86_64.iso"
            scsi:
              scsi0: "{{ item.storage }}:{{ item.diskSize }}"
          loop: "{{ vms }}"
