---
- name: Proxmox Create VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/proxmox.yml
  tasks:
    - name: Create proxmox k8s-7-proxmox-node  VM
      block:
        - name: Create new VM with minimal options and given vmid
          community.general.proxmox_kvm:
            api_user: '{{ username }}@pve'
            api_password: '{{ password }}'
            api_host: "{{ proxmox }}"
            name: test
            node: pve
            storage: "{{ storage }}"