---
- name: Proxmox Create VM
  hosts: proxmox
  gather_facts: false
  vars_files:
    - ../vars/proxmox.yml
  tasks:
    - name: Create proxmox k8s-7-proxmox-node  VM
      block:
        - name: Create new VM with minimal options and given vmid
          community.general.proxmox_kvm:
            api_user: root@pam
            api_password: '{{ password }}'
            api_host: "{{ ansible_ssh_host }}"
            name: test
            node: pve