---
- name: Create a Job Template with Survey
  awx.awx.job_template:
    name: '{{ item.name }}'
    organization: Default
    state: present
    inventory: '{{ awx_inventory_name }}'
    playbook: '{{ item.file }}'
    project: '{{ awx_project_name }}'
    execution_environment: 'Custom EE'
    credentials:
      - 'Host Credentials'
      - 'Vault Credentials'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    survey_enabled: '{{ item.enable_survey }}'
    survey_spec: "{{ lookup('file', '{{item.survey_file}}') }}"
  loop:
    - {
        name: 'Proxmox - Create VM',
        file: playbooks/proxmox/create-vm.yaml,
        enable_survey: true,
        survey_file: 'surveys/create-vm.json',
      }
    - {
        name: 'Proxmox - Attach additional disk to VM',
        file: playbooks/proxmox/attach-additional-disk.yaml,
        enable_survey: true,
        survey_file: 'surveys/attach-additional-disk.json',
      }
    - {
        name: 'Proxmox - Delete VM',
        file: playbooks/proxmox/delete-vm.yaml,
        enable_survey: true,
        survey_file: 'surveys/delete-vm.json',
      }
    - {
        name: 'Proxmox - Mount ISO',
        file: playbooks/proxmox/mount-iso.yaml,
        enable_survey: true,
        survey_file: 'surveys/mount-iso.json',
      }
    - {
        name: 'Proxmox - Start VM',
        file: playbooks/proxmox/start-vm.yaml,
        enable_survey: true,
        survey_file: 'surveys/start-vm.json',
      }
    - {
        name: 'Proxmox - Upload ISO from URL',
        file: playbooks/proxmox/upload-iso.yaml,
        enable_survey: true,
        survey_file: 'surveys/upload-iso.json',
      }
    - {
        name: 'OpenShift - Prepare ACM Cluster ISO',
        file: playbooks/openshift/prepare-acm-iso.yaml,
        enable_survey: true,
        survey_file: '../openshift/surveys/prepare-acm-iso.json',
      }
