---
- name: Create a Job Template with no survey
  awx.awx.job_template:
    name: '{{ item.name }}'
    organization: Default
    state: present
    inventory: '{{ awx_inventory_name }}'
    playbook: '{{ item.file }}'
    project: '{{ awx_project_name }}'
    execution_environment: 'Custom EE'
    credentials:
      - 'Host Credentials'
      - 'Vault Credentials'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
  loop:
    - {
        name: 'OpenShift - ACM GitOps Bootstrap',
        file: playbooks/openshift/acm-gitops-bootstrap.yaml,
      }

    - {
        name: 'OpenShift - Prepare SNO Cluster ISO',
        file: playbooks/openshift/prepare-sno-iso.yaml,
      }
