---
- name: OPNSense Configuration
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: '{{router}}'
      api_credential_file: '/home/runner/.config/opn/opn.key'
      ssl_verify: false
  vars_files:
    - ../vars/router.yml
  tasks:
    - name: Unbound setup
      notify:
        - Reload unbound
      block:
        - name: Adding unbound forwarding
          ansibleguy.opnsense.unbound_forward:
            domain: '{{ item.domain }}'
            target: '{{ item.ip }}'
          loop: "{{ unbound.forwarding }}"

        - name: Adding unbound host
          ansibleguy.opnsense.unbound_host:
            host: '{{ item.host }}'
            domain: '{{ item.domain }}'
            value: '{{ item.value }}'
          loop: "{{ unbound.host }}"

        - name: Adding unbound domain
          ansibleguy.opnsense.unbound_domain:
            domain: '{{ item.domain }}'
            server: '{{ item.server }}'
            state: 'present'
            enabled: true
          loop: "{{ unbound.domain }}"

        - name: Flush
          ansible.builtin.meta: flush_handlers

    - name: Alias setup
      notify:
        - Reload alias
      block:
        - name: Get cloudflare IP's from URI
          ansibleguy.opnsense.alias:
            name: 'cloudflare_ips'
            description: 'Cloudfare IPs'
            type: url
            content: 'https://www.cloudfare.com/ips-v4'
            state: 'present'

        - name: Plex IP
          ansibleguy.opnsense.alias:
            name: 'plex_ip'
            type: host
            content: '{{ alias.plex.ip }}'

        - name: Plex Port
          ansibleguy.opnsense.alias:
            name: 'plex_port'
            type: port
            content: '{{ alias.plex.port }}'

        - name: HASS IoT Devices
          ansibleguy.opnsense.alias:
            name: 'hass_iot_devices'
            type: host
            content: '{{ alias.hass_ips }}'

        - name: Canon Printer IP
          ansibleguy.opnsense.alias:
            name: 'canon_printer'
            type: host
            content: '{{ alias.canon_printer }}'

        - name: NAS IP
          ansibleguy.opnsense.alias:
            name: 'nas_ip'
            type: host
            content: '{{ alias.nas_ip }}'

        - name: Router IP
          ansibleguy.opnsense.alias:
            name: 'router_ip'
            type: host
            content: '{{ router }}'

        - name: Unifi IP
          ansibleguy.opnsense.alias:
            name: 'unifi_ip'
            type: host
            content: '{{ unifi_ip }}'

        - name: TV IPs
          ansibleguy.opnsense.alias:
            name: 'tv_ips'
            type: host
            content: '{{ tv_ips }}'

    - name: "Install Packages"
      block:
        - name: Installing - multiple packages at once
          ansibleguy.opnsense.package:
            name: ['os-theme-rebellion', 'os-mdns-repeater']
            action: 'install'

  handlers:
    - name: Reload alias
      ansibleguy.opnsense.reload:
        target: 'alias'

    - name: Reload unbound
      ansibleguy.opnsense.reload:
        target: 'unbound'
